version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wsq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wsq?schema=public
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: bash -c "npx prisma db push && npx prisma db seed && npm start"

volumes:
  pgdata:
